STATUS_PREPARED = "Prepared"
STATUS_REVIEWED = "Reviewed"
STATUS_QUERIES_RAISED = "Queries raised"
STATUS_APPROVED = "Approved"
STATUS_REJECTED = "Rejected"
STATUS_EXPORTED = "Exported for payment"

APPROVAL_STATUSES = (
    STATUS_PREPARED,
    STATUS_REVIEWED,
    STATUS_QUERIES_RAISED,
    STATUS_APPROVED,
    STATUS_REJECTED,
    STATUS_EXPORTED,
)
